---
- set_fact:
    ingress_enabled: []

- set_fact:
    ingress_enabled:
      - src: ingress/alb-rbac-role.yaml.j2
        dest: "{{ wk_dir }}/ingress-alb-rbac-role.yaml"
      - src: ingress/alb-controller.yaml.j2
        dest: "{{ wk_dir }}/ingress-alb-controller.yaml"

- include: setup.yml
