---

- name: Generate ingress config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ ingress_enabled }}"

- name: Deploy ingress controller
  shell: |
    KUBECONFIG={{ eks_client_kubeconfig_file }} {{ eks_client_kubectl_path }} apply -f {{ item.dest }}
  register: ret_setup_ingress
  with_items: "{{ ingress_enabled }}"

- debug: var=ret_setup_ingress
